In [96]:
from PIL import Image
import numpy as np
import os, os.path
import glob
import pylab

In [82]:
######################################### Loading Images from a Directory###########################################


image_list = []
for filename in glob.glob('/home/sabeeh/Desktop/MRC_A_003/data/training/*.pgm'): 
    im=Image.open(filename)
    image_list.append(im)

############################################### Initial Image #######################################################

sample_1 = image_list[0]
im_1 = np.asarray(sample_1)
flat_1 = im_1.flatten('C')
flat_1 = flat_1.reshape(45045,1)

###################Appending Each Image to make one Matrix i-e one column represents one Image######################

for count in range(1,110):
    sample_2 = image_list[count]
    im_2 = np.asarray(sample_2)
    flat_2 = im_2.flatten('C')
    flat_2 = flat_2.reshape(45045,1)
    flat_1 = np.append(flat_1,flat_2,1)


array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ..., 
       [188, 255, 255, ..., 255, 242, 244],
       [202, 255, 255, ..., 255, 227, 234],
       [202, 255, 255, ..., 255, 207, 255]], dtype=uint8)

In [84]:
#################################################    MEAN   #######################################################

mean_image = np.mean(flat_1,1)
mean_image

array([ 244.71818182,  244.9       ,  245.13636364, ...,  217.61818182,
        217.95454545,  219.16363636])

In [110]:
################################################# SUBTRACT ########################################################

sub_init = flat_1[:,0] - mean_image
sub_init = sub_init.reshape(45045,1)

for subtract in range(1,110):
    sub_final = flat_1[:,subtract] - mean_image
    sub_final = sub_final.reshape(45045,1)
    sub_init = np.append(sub_init,sub_final,1)


sub_init[:,0].shape

(45045,)

In [91]:
#################################################TRANSPOSE########################################################
transpose_image = sub_init.T

In [94]:
#################################################   SVD########################################################

U,S,V = np.linalg.svd(transpose_image, full_matrices=0)

In [97]:
pylab.figure()

In [111]:
pylab.gray()
##pylab.imshow((sub_init[0]).reshape(231,195))
b = sub_init[:,0].reshape(231,195)

In [112]:
pylab.imshow(b)

In [113]:
pylab.show()

In [114]:
U.shape

(110, 110)

In [115]:
U[0]

array([ -1.26813061e-01,   1.47909843e-02,  -7.47565885e-02,
         3.21634261e-03,  -6.22901240e-02,   9.04438946e-02,
         7.41479623e-02,  -2.95080609e-02,   1.17983487e-02,
        -3.20978108e-02,   1.13729074e-01,  -5.97432873e-02,
         2.15059003e-02,  -1.56590777e-01,   1.78254169e-02,
        -7.44870109e-02,   1.46826375e-01,  -5.50479236e-02,
         3.37432843e-03,   5.93754112e-02,  -9.47656383e-02,
         4.73040824e-03,  -1.39195063e-03,   7.39616936e-02,
        -4.52458636e-02,   6.76639276e-03,  -5.66974007e-02,
         3.20489382e-02,  -2.64782561e-01,   4.37429492e-02,
        -1.31728275e-01,   1.91929659e-01,  -1.86113744e-01,
         1.05936388e-01,  -7.37079725e-02,   2.13745882e-01,
        -9.85418780e-02,  -4.29275857e-02,  -1.63823208e-01,
         5.84028804e-02,   1.27783076e-01,   3.64391956e-02,
        -5.79399398e-02,  -6.97608931e-02,   1.92791555e-01,
         2.77614142e-02,   2.90488883e-03,   1.10641583e-01,
        -1.05406327e-01,