In [1]:
from PIL import Image
import numpy as np
import pylab
import os

In [46]:
path = "/home/saikiran/HBRS/MRC/week3/MRC_A_003/data/training/"
i = 0
#for file in sorted(os.listdir(path)):
#    print file
allimagematrix = np.asarray([np.array(Image.open("/home/saikiran/HBRS/MRC/week3/MRC_A_003/data/training/%s" % file)).flatten() for file in sorted(os.listdir(path))])

In [47]:
print allimagematrix.shape

(110, 45045)


In [4]:
allimagematrix[0].shape

(45045,)

In [5]:
allimagematrix.shape

(110, 45045)

In [6]:
mean = allimagematrix.mean(axis = 0)

In [7]:
mean

array([ 244.71818182,  244.9       ,  245.13636364, ...,  217.61818182,
        217.95454545,  219.16363636])

In [8]:
mean.shape

(45045,)

In [9]:
#for i in range(110):
imagesminmean = allimagematrix - mean
    

In [10]:
imagesminmean

array([[  10.28181818,   10.1       ,    9.86363636, ...,   37.38181818,
          37.04545455,   35.83636364],
       [  10.28181818,   10.1       ,    9.86363636, ...,   37.38181818,
          37.04545455,   35.83636364],
       [ -81.71818182,  -57.9       ,  -63.13636364, ...,  -32.61818182,
         -17.95454545,   -8.16363636],
       ..., 
       [  10.28181818,   10.1       ,    9.86363636, ...,   37.38181818,
          37.04545455,   35.83636364],
       [-122.71818182, -121.9       , -121.13636364, ...,   37.38181818,
          37.04545455,   35.83636364],
       [  10.28181818,   10.1       ,    9.86363636, ..., -181.61818182,
        -179.95454545, -179.16363636]])

In [11]:
imagesminmean.shape

(110, 45045)

In [12]:
U,S,V = np.linalg.svd(imagesminmean.T,full_matrices=0)

In [13]:
print U

[[ -1.06011077e-03   3.32349551e-04  -2.41204699e-03 ...,  -6.48927886e-04
    8.00832510e-04   1.30860049e-01]
 [ -9.83361777e-04   2.79298235e-04  -2.28440845e-03 ...,  -8.19125728e-04
    1.06347052e-03  -1.87076628e-01]
 [ -1.00171563e-03   2.35103963e-04  -2.22569516e-03 ...,  -6.69787061e-04
    9.08614963e-04   5.90573389e-01]
 ..., 
 [  4.78130773e-03   3.80725039e-03  -4.32862120e-04 ...,  -1.56743039e-03
    5.68414401e-04  -8.81243597e-04]
 [  4.72126946e-03   4.03907436e-03  -4.72014531e-04 ...,  -1.67753714e-03
    1.48137416e-04  -2.42166625e-03]
 [  4.57532517e-03   4.09620656e-03  -4.74279260e-04 ...,   3.71170305e-04
    3.99303054e-04   1.85528805e-03]]


In [14]:
U.shape




#tmp = np.dot(allimagematrix.T,eigenvectors).T
#tmp

(45045, 110)

In [57]:
w = np.dot(imagesminmean,U)
w.shape

(110, 110)

In [16]:
w[0,:].sum()

-359.67032579751088

In [17]:
test_dim = np.array([np.array(Image.open("/home/saikiran/HBRS/MRC/week3/MRC_A_003/data/test/subject01.happy.pgm")).flatten()])

In [18]:
test_dim.shape

(1, 45045)

In [19]:

shifted_in = test_dim - mean

In [20]:
U_t,S_t,V_t = np.linalg.svd(shifted_in.T,full_matrices=0)

In [48]:
U_t.shape

(45045, 1)

In [21]:
w_t = np.dot(shifted_in,U)

In [22]:
w_t.size

110

In [23]:
import scipy.spatial as sp

In [24]:
dist = np.empty(110)

for i in range(110):
    dist[i] = (sp.distance.euclidean(w[i],w_t))

In [25]:
np.argmin(dist)

4

In [26]:
dist



array([  6098.55861738,   6028.65567184,  20863.06385001,   6640.93074874,
         4358.29269434,   7469.05423796,   9909.71337676,  13901.87890933,
        13947.22525127,  18458.22359301,  14259.96340141,  14190.58649984,
        15531.83553897,  13601.20565279,  15641.33300616,  13247.08572515,
        16795.28988168,  17197.73125181,  15043.51229632,  24264.26455118,
        13378.49988637,  13474.66709086,  24377.61875593,  13241.99475946,
        17408.12333968,  15071.29089393,  15386.39818832,  22020.55381251,
        15394.0960829 ,  14709.70228147,  15550.41385975,  15938.58375796,
        15728.48899957,  14669.86578703,  19830.38734391,  15652.47313397,
        15280.40589152,  14789.08895807,  15188.91326625,  14546.36347028,
        15000.90374643,  18649.55241312,  15263.46203224,  16150.04458847,
        16583.19867244,  16182.30521927,  16590.12622645,  23575.78469976,
        17185.397092  ,  21822.89387798,  17033.36790566,  17957.82515255,
        16359.01544133,  

In [28]:
allimagematrix[4].shape

(45045,)

In [32]:
test_dim = np.array(Image.open("/home/saikiran/HBRS/MRC/week3/MRC_A_003/data/test/subject01.happy.pgm"))
test_dim.shape

(231, 195)

In [34]:
pic = allimagematrix[4].reshape(231,195)

In [35]:
pylab.figure()
pylab.gray()
pylab.imshow(pic)

In [37]:
pylab.show()

In [39]:
allimagematrix[4].shape

(45045,)

In [40]:
image_filenames = ("smiling", "sad", "idonno")

In [41]:
for image in image_filenames:
    print image

smiling
sad
idonno


In [45]:
for file in sorted(os.listdir(path)):
    print file
    allimagematrix = np.asarray([np.array(Image.open("/home/saikiran/HBRS/MRC/week3/MRC_A_003/data/training/%s" % file)).flatten()])

subject01.glasses.pgm
subject01.noglasses.pgm
subject01.rightlight.pgm
subject01.sad.pgm
subject01.sleepy.pgm
subject01.surprised.pgm
subject01.wink.pgm
subject02.centerlight.pgm
subject02.glasses.pgm
subject02.leftlight.pgm
subject02.noglasses.pgm
subject02.normal.pgm
subject02.rightlight.pgm
subject02.sad.pgm
subject02.sleepy.pgm
subject02.surprised.pgm
subject02.wink.pgm
subject03.glasses.pgm
subject03.happy.pgm
subject03.leftlight.pgm
subject03.noglasses.pgm
subject03.normal.pgm
subject03.rightlight.pgm
subject03.sad.pgm
subject03.wink.pgm
subject04.happy.pgm
subject04.normal.pgm
subject04.rightlight.pgm
subject04.sad.pgm
subject04.sleepy.pgm
subject04.surprised.pgm
subject04.wink.pgm
subject05.glasses.pgm
subject05.happy.pgm
subject05.leftlight.pgm
subject05.noglasses.pgm
subject05.sleepy.pgm
subject05.surprised.pgm
subject05.wink.pgm
subject06.centerlight.pgm
subject06.noglasses.pgm
subject06.rightlight.pgm
subject06.sad.pgm
subject06.sleepy.pgm
subject06.surprised.pgm
subject07.

In [43]:
allimagematrix

array([[255, 255, 255, ...,  36,  38,  40]], dtype=uint8)

In [44]:
allimagematrix.shape

(1, 45045)

In [52]:
global x 

In [53]:
x = allimagematrix

In [54]:
x.shape

(110, 45045)