In [2]:

import numpy
import matplotlib
from matplotlib import pylab, mlab, pyplot
np = numpy
plt = pyplot
            
from IPython.display import display
from IPython.core.pylabtools import figsize, getfigs
import IPython
from pylab import *
from numpy import *
import os

In [ ]:
#note that for this code, inuput can be any of the points, dont freak out ;-), i m pretty sure about it it works in awesome way just follow the algorithm
# check for the commments where code for different excercises end
# code to fit two parallel lines
#also to understand why the inverting happens and sonetimes it doesnt check out the downloads in lea

In [3]:
p1= np.load('/home/sabeeh/Desktop/MRC_A_004/data/P1.npy')
p2= np.load('/home/sabeeh/Desktop/MRC_A_004/data/P2.npy')
print p1

[[   0.          -12.68293924]
 [   1.          -12.61393325]
 [   2.          -13.54072672]
 ..., 
 [ 697.         -783.54143988]
 [ 698.         -784.76854525]
 [ 699.         -786.81395933]]


In [4]:
print p1.shape
print p2.shape

(700, 2)
(450, 2)


In [5]:
sizep1toappend, sizep1columns = p1.shape
sizep2toappend, sizep2columns = p2.shape

In [6]:
onesp1 = np.ones((sizep1toappend,1))
zerosp1 = np.zeros((sizep1toappend,1))
onesp2  = np.ones((sizep2toappend,1))
zerosp2 = np.zeros((sizep2toappend,1))

In [7]:
print onesp1.shape
print zerosp1.shape
print onesp2.shape
print zerosp2.shape

(700, 1)
(700, 1)
(450, 1)
(450, 1)


In [8]:
completep1 = np.hstack((onesp1,zerosp1,p1))
print completep1.shape

(700, 4)


In [9]:
completep2 = np.hstack((onesp2,zerosp2,p2))
completep2.shape

(450, 4)

In [10]:
A = np.vstack((completep1,completep2))

In [35]:
A

array([[   1.        ,    0.        ,    0.        ,  -12.68293924],
       [   1.        ,    0.        ,    1.        ,  -12.61393325],
       [   1.        ,    0.        ,    2.        ,  -13.54072672],
       ..., 
       [   1.        ,    0.        ,  447.        , -388.30994665],
       [   1.        ,    0.        ,  448.        , -388.54277472],
       [   1.        ,    0.        ,  449.        , -388.51291723]])

In [57]:
def clsq(A,dim):
    m, p = A.shape
    if p < dim + 1:
        print "not enough unknowns"
    if m < dim:
        print "not enough equations"
    m = np.minimum(m,p)
    Not,R  = np.linalg.qr(A)
    R1 = R[p-dim:m, p-dim:p] 
    U,S,V = np.linalg.svd(R1,full_matrices=False)
    n = np.array(V[:,dim-1]).reshape(2,1)
    #R1 = np.linalg.inv(-R[0:p-dim, 0:p-dim])
    #print R1
    a = np.dot(R1,n)
    c = np.dot(np.linalg.inv(R1),a)
    return c,n

array([[ 0.65686221, -0.75401063],
       [ 0.75401063,  0.65686221]])

In [17]:
c,n = clsq(A,2)
print c
print n
print n[0]*n[0] + n[1]*n[1]

[[-0.75401063]
 [ 0.65686221]]
[[-0.75401063]
 [ 0.65686221]]
[ 1.]


In [12]:
#nothing much dont run this is just experimenting block


dim = 2
p = 4
Not,R  = np.linalg.qr(A)
R1 = -R[2:4,2:4]
U,S,V = np.linalg.svd(R1,full_matrices=False)
print V.shape
print V
n = V[:,1]
print n
print R1
print R1[0:p-dim,p-dim:p]

(2, 2)
[[-0.65686221  0.75401063]
 [-0.75401063 -0.65686221]]
[ 0.75401063 -0.65686221]
[[-6353.91306015  7156.94952258]
 [   -0.         -1317.16887911]]
[]


In [31]:
# same expeimenting block

print R
R1 = -R[2:4, 2:4]
print R1

[[   -33.91164992      0.         -10193.39963877  10737.67477556]
 [     0.              0.           -290.97702381    295.31644932]
 [     0.              0.           6353.91306015  -7156.94952258]
 [     0.              0.              0.           1317.16887911]]
[[-6353.91306015  7156.94952258]
 [   -0.         -1317.16887911]]


In [ ]:
# code to fit two perpendicular lines

In [21]:
q1= np.load('/home/saikiran/HBRS/MRC/week4/MRC_A_004/data/Q1.npy')
q2= np.load('/home/saikiran/HBRS/MRC/week4/MRC_A_004/data/Q2.npy')
print q1.shape
print q2.shape

(900, 2)
(450, 2)


In [22]:
sizeq1toappend, sizeq1columns = q1.shape
sizeq2toappend, sizeq2columns = q2.shape

In [23]:
onesq1 = np.ones((sizeq1toappend,1))
zerosq1 = np.zeros((sizeq1toappend,1))
onesq2  = np.ones((sizeq2toappend,1))
zerosq2 = np.zeros((sizeq2toappend,1))
print onesq1.shape
print zerosq1.shape
print onesq2.shape
print zerosq2.shape

(900, 1)
(900, 1)
(450, 1)
(450, 1)


In [25]:
completeq1 = np.hstack((onesq1,zerosq1,q1))
print completeq1.shape

(900, 4)


In [40]:
print q2.shape
toinvertq2_1 = np.array(q2[:,0]*-1).reshape(sizeq2toappend,1)
toinvertq2_2 = np.array(q2[:,1]).reshape(sizeq2toappend,1)
print toinvertq2_1.shape
print toinvertq2_2.shape

(450, 2)
(450, 1)
(450, 1)


In [41]:
completeq2 = np.hstack((onesq2,zerosq2,toinvertq2_2, toinvertq2_1))
completeq2.shape

(450, 4)

In [43]:
Perpendi = np.vstack((completeq1,completeq2))
Perpendi.shape

(1350, 4)

In [44]:
#call the same function clsq(A,dim)
c2,n2 = clsq(Perpendi,2)

In [45]:
print c2
print n2

[[-0.70782211]
 [-0.70639073]]
[[-0.70782211]
 [-0.70639073]]


In [46]:
print n2[0]*n2[0]+n2[1]*n2[1]

[ 1.]


In [47]:
#code ends and works awesomely

In [48]:
#code to fit rectangle

In [50]:
# it must have four points

p1= np.load('/home/saikiran/HBRS/MRC/week4/MRC_A_004/data/P1.npy')
q1= np.load('/home/saikiran/HBRS/MRC/week4/MRC_A_004/data/Q1.npy')
rect= np.load('/home/saikiran/HBRS/MRC/week4/MRC_A_004/data/R2.npy')
sect= np.load('/home/saikiran/HBRS/MRC/week4/MRC_A_004/data/S2.npy')
print p1.shape
print q1.shape
print rect.shape
print sect.shape

(700, 2)
(900, 2)
(450, 2)
(450, 2)


In [51]:
sizep1toappend, sizep1columns = p1.shape
sizeq1toappend, sizeq1columns = q1.shape
sizerecttoappend, sizerectcolumns = rect.shape
sizesecttoappend, sizesectcolumns = sect.shape

In [52]:
onesp1 = np.ones((sizep1toappend,1))
zerosp1 = np.zeros((sizep1toappend,1))
onesq1 = np.ones((sizeq1toappend,1))
zerosq1 = np.zeros((sizeq1toappend,1))
onesrect = np.ones((sizerecttoappend,1))
zerosrect = np.zeros((sizerecttoappend,1))
onessect  = np.ones((sizesecttoappend,1))
zerossect = np.zeros((sizesecttoappend,1))

In [54]:
toinvertq1_1 = np.array(q1[:,0]*-1).reshape(sizeq1toappend,1)
toinvertq1_2 = np.array(q1[:,1]).reshape(sizeq1toappend,1)
print toinvertq1_1.shape
print toinvertq1_2.shape
toinvertsect_1 = np.array(sect[:,0]*-1).reshape(sizesecttoappend,1)
toinvertsect_2 = np.array(sect[:,1]).reshape(sizesecttoappend,1)
print toinvertsect_1.shape
print toinvertsect_2.shape

(900, 1)
(900, 1)
(450, 1)
(450, 1)


In [56]:
completep1 = np.hstack((onesp1,zerosp1,p1))
completeq1 = np.hstack((onesq1,zerosq1,toinvertq1_2, toinvertq1_1))
completerect = np.hstack((onesrect,zerosrect,rect))
completesect = np.hstack((onessect,zerossect,toinvertsect_2, toinvertsect_1))


In [57]:
Rectangle = np.vstack((completep1,completeq1,completerect,completesect))

In [58]:
#call our awesome function and vola you have your c and n again
c3,n3 = clsq(Rectangle,2)


In [60]:
print  c3
print n3

[[-0.85530347]
 [ 0.51812738]]
[[-0.85530347]
 [ 0.51812738]]


In [61]:
print n3[0]*n3[0]+n3[1]*n3[1]

[ 1.]


In [ ]:
#Finally :)