In [1]:
import numpy as np
from scipy import spatial
import numpy
import matplotlib
from matplotlib import pylab, mlab, pyplot
np = numpy
plt = pyplot

from IPython.display import display
from IPython.core.pylabtools import figsize, getfigs
import IPython

from pylab import *
from numpy import *

In [2]:
x = np.loadtxt('/home/sabeeh/Desktop/MRC_A_002/data/cloud.asc')
x.shape

(219435, 3)

In [3]:
i= x[0:219435, ]
tree = spatial.cKDTree(i)


for row in range(0,219435):
    globals()['string%s' % row] = tree.query_ball_point(i[row],0.04,2)

for row in range(0,219435):
    globals()['meanset%s' % row] = np.empty([1,3])#np.matrix([[0,0,0]])
    
    for internal in range(0,len(globals()['string%s' %row])):
        if(len(globals()['string%s' %row])<=1):
            pass
            
        else:
            globals()['meanset%s' % row] = np.vstack((globals()['meanset%s' % row],x[globals()['string%s' %row][internal]]))
    globals()['meanset%s' % row] = np.delete(globals()['meanset%s' % row],0,0)

In [49]:
i[761]

array([ 0.40528536, -2.15999985,  5.30817652])

In [4]:
for j in range(0,219435):
    if((globals()['meanset%s' % j]).shape == (0,3)):
        pass
    else:
        a=globals()['meanset%s' % j].mean(0)
        globals()['x%s' % j]=np.matrix(a)
        
    

In [19]:
x761

matrix([[ nan,  nan,  nan]])

In [5]:
for row in range(0,219435):
    for internal in range(0,len(globals()['string%s' % row])):
        if(((globals()['meanset%s' %row]) == [[ nan,  nan,  nan]]).all()):
            #globals()['meanset%s' %row][internal] = globals()['meanset%s' %row-1]
            pass
        else:
            globals()['meanset%s' % row][internal]=globals()['meanset%s' % row][internal] - globals()['x%s' % row]
        

In [24]:
meanset761

array([], shape=(0, 3), dtype=float64)

In [6]:
angle = np.empty([219435])
for row in range(0,219435):
    #globals()['n%s' %row] = np.outer(globals()['meanset%s' % row].T,globals()['meanset%s' % row])
    if((globals()['meanset%s' % j]).shape == (0,3)):
        pass
    else:
        globals()['n%s' %row] = np.cov(globals()['meanset%s' % row].T)
       
    

/home/sabeeh/anaconda/lib/python2.7/site-packages/numpy/lib/function_base.py:1890: RuntimeWarning: Degrees of freedom <= 0 for slice
  warnings.warn("Degrees of freedom <= 0 for slice", RuntimeWarning)
/home/sabeeh/anaconda/lib/python2.7/site-packages/numpy/core/_methods.py:59: RuntimeWarning: Mean of empty slice.
  warnings.warn("Mean of empty slice.", RuntimeWarning)
/home/sabeeh/anaconda/lib/python2.7/site-packages/numpy/core/_methods.py:69: RuntimeWarning: invalid value encountered in true_divide
  ret, rcount, out=ret, casting='unsafe', subok=False)
/home/sabeeh/anaconda/lib/python2.7/site-packages/numpy/lib/function_base.py:1901: RuntimeWarning: invalid value encountered in true_divide
  return (dot(X, X.T.conj()) / fact).squeeze()


In [8]:
meanset761

array([], shape=(0, 3), dtype=float64)

In [7]:
angle = np.empty([219435])
for row in range(0,219435):
    if((globals()['meanset%s' % row]).shape == (0,3)):
        pass
    else:
        (w,v) = np.linalg.eig(globals()['n%s' % row])
        mini_vector = v[:,np.argmin(w)]
        pro = mini_vector*mini_vector
        mag  = np.sqrt(np.absolute(pro[0]+pro[1]+pro[2]))
        dotproduct = np.dot(mini_vector, [0,0,1])
        #print dotproduct
        angle[row] = np.arccos(dotproduct/mag)
    
    
    

/home/sabeeh/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:12: ComplexWarning: Casting complex values to real discards the imaginary part


In [17]:
n761

array([[ nan,  nan,  nan],
       [ nan,  nan,  nan],
       [ nan,  nan,  nan]])

In [8]:
colors = cm.RdYlGn_r(angle)

retcol = colors[:,:3] *255

final = np.append(i,retcol,axis=1)

In [9]:
def save_as_ply(filename, points):
    assert points.ndim == 2
    assert points.shape[1] == 6
    header = """ply
        format ascii 1.0
        element vertex {0}
        property float x
        property float y
        property float z
        property uchar red
        property uchar green
        property uchar blue
        element face 0
        property list uchar int vertex_indices\r\nend_header"""
    number_of_points = points.shape[0]
    with open(filename, "w") as ply_file:
        print >>ply_file, header.format(number_of_points)
        point_format = ("%.18f", "%.18f", "%.18f", "%d", "%d", "%d") 
        np.savetxt(ply_file, points, delimiter=" ", fmt=point_format)
        
save_as_ply("output.ply",final)

In [11]:
scalarMap = matplotlib.cm.ScalarMappable(norm=norm, cmap=jet)
print scalarMap.get_clim()

(0, 4)


In [36]:
lines = []
for idx in range(len(curves)):
    line = curves[idx]
    colorVal = scalarMap.to_rgba(values[idx])
    colorText = (
        'color: (%4.2f,%4.2f,%4.2f)'%(colorVal[0],colorVal[1],colorVal[2])
        )
    retLine, = ax.plot(line,
                       color=colorVal,
                       label=colorText)
    lines.append(retLine)

-0.137194628913


1.7084250304193187

In [38]:
np.cos(1.708)

-0.13677360515552331